### ISSUE TITLE
Black screen after boot, backlight works, verified acceleration is working using VNC

### ISSUE THREAD

**Issue by deorder** [thefat32/N56VB-Hackintosh-OpenCore#1]
Thank you for releasing all those files. Your files really helped me to get my setup working and to install Catalina.

I have a N56VZ, so there could be a difference, but I am not able to get any image on the screen.
The backlight is on, I can even press Fn + F5/F6 to change it and I verified that the video driver is working (using System Report) with acceleration + metal support using the correct resolution by logging in using VNC.
I tried forcing all combinations of device-ids, ig-platform-ids and experimented with the framebuffer patch settings without luck.

Hackintool says the following using what is autodetected by WhateverGreen (when no device-id or ig-platform-id is set):
```
Current Framebuffer:
Model: MacbookPro10,1
Intel Generation: Ivy Bridge
Platform ID: 0x01660003
GPU Device ID: 0x01668086
GPU Name: Intel HD Graphics 4000
```

![IMG_20200719_021852](https://user-images.githubusercontent.com/31899960/87864274-9ca30d00-c966-11ea-82e2-2d3920a61796.jpg)
![IMG_20200719_021915](https://user-images.githubusercontent.com/31899960/87864277-a9276580-c966-11ea-93d2-cd4775da9f2e.jpg)
![IMG_20200719_021753](https://user-images.githubusercontent.com/31899960/87864267-7d0be480-c966-11ea-9fed-230c32e6e229.jpg)
![IMG_20200719_022025](https://user-images.githubusercontent.com/31899960/87864311-fb688680-c966-11ea-9608-53a5983e36ae.jpg)

The WhateverGreen debug log:
```
(DBG) WhateverGreen bootstrap DBG-140-2020-06-01
(DBG) not enabling CAIL_DisableDrmdmaPowerGating
(DBG) not enabling CAIL_DisableGfxCGPowerGating
(DBG) not enabling CAIL_DisableUVDPowerGating
(DBG) not enabling CAIL_DisableVCEPowerGating
(DBG) not enabling CAIL_DisableDynamicGfxMGPowerGating
(DBG) not enabling CAIL_DisableGmcPowerGating
(DBG) not enabling CAIL_DisableAcpPowerGating
(DBG) not enabling CAIL_DisableSAMUPowerGating
(DBG) applying backlight patch
(DBG) panel display set returned 1
```

I verified that the kernel extension was loaded:
```
49    0 0xffffff7f832d5000 0x91000    0x91000    as.vit9696.WhateverGreen (1.4.0) 0077B2DD-3D40-3425-9F00-C3A09AC397FB <43 13 8 6 5 3 2 1>
```

The VRAM to be reserved set in my BIOS is 64MB (which is the max). I can only get something on the screen when I prevent MacOSX from loading a video driver by deliberately providing a wrong ID so it will use VESA. That is how I was able to install Catalina. 

So everything seems to work except that the screen is black. Do you have any idea what could be wrong?

**Comment by deorder** [comment]
Got it to work on my N56VZ. I use all of your files as follows.

The following kernel extensions:
```
ACPIKeyboard.kext
AppleALC.kext
ApplePS2SmartTouchPad.kext
AsusSMC.kext
AtherosE2200Ethernet.kext
Display-4ca3-314c.kext
IntelGraphicsFixup.kext
Lilu.kext
NoTouchID.kext
SMCBatteryManager.kext
SMCLightSensor.kext
SMCProcessor.kext
SMCSuperIO.kext
SSDT-PNLF.dsl
USBInjectAll.kext
VirtualSMC.kext
VoodooI2C.kext
VoodooI2CAtmelMXT.kext
VoodooI2CELAN.kext
VoodooI2CFTE.kext
VoodooI2CHID.kext
VoodooI2CSynaptics.kext
VoodooPS2Controller.kext
WhateverGreen.kext
WhateverGreen.kext.release
```

The following drivers:
```
ApfsDriverLoader.efi
HfsPlus.efi
OpenRuntime.efi
```

Here is my plist (I removed the serial, uuid etc.):
[config.plist.zip](https://github.com/thefat32/N56VB-Hackintosh-OpenCore/files/4945563/config.plist.zip)

I am not sure what made it work, but it could have been the combination of using the right ig-platform-id and EDID. I also did a BIOS reset from inside the BIOS itself, so that could have been it as well.

**Comment by thefat32** [comment]
Great, closing this as you have solved it
